name: Release

on:
  push:
    branches: [master]

jobs:
  release-to-npm:
    name: NPM
    uses: node-modules/github-actions/.github/workflows/npm-release.yml@master

  release-to-jsr:
    name: JSR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    needs:
      - release-to-npm

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Publish package
        run: npx jsr publish
